# -*- coding: utf-8 -*-
"""diabetes_mellitus_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1saloC-0BsJyRSxG9dfNySX4E8fW9jT9g
"""

# Import Libraries

import matplotlib
import numpy as np
import pandas as pd
from pandas import read_csv
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection, metrics
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, cross_val_score, KFold, learning_curve, StratifiedKFold
from google.colab import drive
drive.mount('/content/gdrive')

import warnings
warnings.filterwarnings("ignore")

# Inspect the data

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
dataset = read_csv('gdrive/My Drive/diabetes_prediction_dataset.csv')

# Print First 10 and last 10 rows
print(dataset.head(10))
print(dataset.tail(10), "\n")

# All features are numeric except for "gender" and "smoking_history"
print(dataset.describe(), "\n")
print(dataset.info(), "\n")

# Checking out smoking_history and gender as it's non-numeric
print(dataset["smoking_history"].value_counts())
print(dataset["gender"].value_counts(), "\n")

# Transform dataset to numeric dataset with LabelEncoder
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
dataset["smoking_history"] = label_encoder.fit_transform(dataset["smoking_history"])
dataset["gender"] = label_encoder.fit_transform(dataset["gender"])

print(dataset.info(), "\n")

# There are still 35,000 "No Info" values in the smoking_history feature, which is concerning
# We find out that smoking_history is not highly correlated with any given outcome
g = sns.heatmap(dataset.corr(),annot=True, linewidths=0.5, fmt='.2f', cmap='BrBG')
plt.show()

# Histrogram to show the distribution
p = dataset.hist(figsize = (20,20))
plt.show()

# Diabetes outcome is imbalanced: ~90/10
print(dataset["diabetes"].value_counts())

# Data resampling
from imblearn.over_sampling import SVMSMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

feats_X = dataset.iloc[:, [0,1,2,3,4,5,6,7]]
trgt_y = pd.DataFrame(dataset.iloc[:, 8])

""" # Testing SVMSMOTE Oversampler
svm_smote = SVMSMOTE(sampling_strategy='not majority', k_neighbors=5)
print("Oversampling minority class... ", end='')
resmpl_X, resmpl_y = svm_smote.fit_resample(feats_X, trgt_y)
print("Done!\n")
"""
"""# Testing Random oversampler
ros = RandomOverSampler(random_state=42)
print("Oversampling minority class... ", end='')
resmpl_X, resmpl_y = ros.fit_resample(feats_X, trgt_y)
print("Done!\n")
"""
# Testing Random undersampler
rus = RandomUnderSampler(random_state=42)
print("Undersampling majority class... ", end='')
resmpl_X, resmpl_y = rus.fit_resample(feats_X, trgt_y)
print("Done!\n")

print(resmpl_X.info(), "\n")
print(resmpl_X.head(), "\n") #1st 5 rows
print(resmpl_X.tail(), "\n") #last 5 rows

# Outcome is now balanced
print(resmpl_y["diabetes"].value_counts())

# Feature Engineering -> Feature Selection
from sklearn.feature_selection import SelectKBest, f_classif

# Relevant/Good: features(Independent/Input) --high +/-ve correlation--> target(Dependent/Output)
# Irrelevant/Bad: features(Independent/Input) --low near-0 correlation--> target(Dependent/Output)
feats_X = resmpl_X
trgt_y = resmpl_y
print("Resampled_X:", resmpl_X.shape, ",\t", "Resampled_y:", resmpl_y.shape, "\n")

# 'SelectKBest' Feature-Selection strategy
for t in range(trgt_y.shape[1]):
  KBest = SelectKBest(score_func=f_classif, k=5)  # Classification(chi2|f_classif|mutual_info_classif); Regression(r_regression|f_regression|mutual_info_regression)
  output = KBest.fit_transform(feats_X, trgt_y.iloc[:,t])  # Fits to data & transform/reduce it to the selected features
  top_feats_X_1 = pd.DataFrame(output, columns=KBest.get_feature_names_out())  # Transfrom numpy-array 2 pandas-dataframe
  print(top_feats_X_1.head(), "\n") #1st 5 rows
  print(top_feats_X_1.tail()) #last 5 rows

sns.heatmap(top_feats_X_1.corr(), annot=True, linewidths=0.5, fmt='.2f', cmap='BrBG')
plt.show()

# Ignore this section, SelectKBest returns better features
# AVOID Multi-Collinearity/Redundancy: features(Independent/Input) --high +/-ve correlation--> features(Independent/Input)
useful_feats_X = dataset.loc[:, ["age", "hypertension", "heart_disease", "bmi", "HbA1c_level", "blood_glucose_level"]]
useful_feats_corr = useful_feats_X.corr()  # Linear(pearson) to target; Nonlinear(kendall|spearman) to target
plt.figure(figsize=(6, 5))
sns.heatmap(useful_feats_corr, annot=True, linewidths=0.5, fmt='.2f', cmap='BrBG')
plt.show()  # figsize(inch, inch); (-ve corr., 0, +ve corr.)

useful_feats_X = dataset.loc[:, ["hypertension", "heart_disease", "bmi", "HbA1c_level", "blood_glucose_level"]]
useful_feats_corr = useful_feats_X.corr()  # Linear(pearson) to target; Nonlinear(kendall|spearman) to target
plt.figure(figsize=(6, 5))
sns.heatmap(useful_feats_corr, annot=True, linewidths=0.5, fmt='.2f', cmap='BrBG')
plt.show()  # figsize(inch, inch); (-ve corr., 0, +ve corr.)

# Training & Test Sets: train_test_split

# X = feats_X.loc[:, ["hypertension", "heart_disease", "bmi", "HbA1c_level", "blood_glucose_level"]]
X = top_feats_X_1.loc[:, :]
y = trgt_y  # Using "diabetes" to ensure data(Train|Test) contain fair samples of this feature

print(X.describe())
print(y.describe())
print(X.shape)
print(y.shape, "\n")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train:", X_train.shape, ",\t", "y_train:", y_train.shape)
print("X_test:", X_test.shape, ",\t", "y_test:", y_test.shape)

# Features' Standardization AND Samples' Normalization ("skewness/unsymmetric" dataset)
from sklearn.preprocessing import QuantileTransformer, StandardScaler, MinMaxScaler, Normalizer

# STANDARDIZATION (Column-wise): Non-Linear Transformation for 'feats_X'
# 'QuantileTransformer()' transforms features (columns) with 'skewed/congested' or 'highly-spread' data into a uniform(0..1)/normal(-1..0..+1) distr.
quantile_trans_standzatn = QuantileTransformer(output_distribution='uniform')
quantile_trans_standzatn = quantile_trans_standzatn.fit(X_train)  # Fit ONLY on data(Train) to avoid 'data-leak' & 'bias' from data(Test)
standized_X_train = quantile_trans_standzatn.transform(X_train)
standized_X_test = quantile_trans_standzatn.transform(X_test)

# STANDARDIZATION (Column-wise): Linear Transformation for 'classifier_y'
# Requires NO transformation for 'trgt_y' cos it already contains values(Binary)
standized_y_train = y_train
standized_y_test = y_test
# Histrogram shows dataset WITHOUT 'skewness' (data is uniformly distributed)
pd.DataFrame(standized_X_train, columns=X_train.columns).hist(bins=50, figsize=(14, 13))
plt.show()

# Select ML/DL algorithm AND Tune/Re-tune hyperparameters
from sklearn.multioutput import MultiOutputRegressor, MultiOutputClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression, SGDClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB, CategoricalNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

ml_algorithm = "RandFrst"  # KNN, GradBoost, RandFrst, ExtraTree, DeciTree, etc

if (ml_algorithm == "LinearRegress"):
  algorithm = MultiOutputClassifier(LinearRegression())  # For regression only
elif (ml_algorithm == "LogisticRegress"):
  algorithm = MultiOutputClassifier(LogisticRegression(solver='lbfgs'))  # For classification only
elif (ml_algorithm == "SuppVec"): # NOT WORKING
  algorithm = MultiOutputClassifier(SVC())
elif (ml_algorithm == "StochastGrad"): # NOT WORKING
  algorithm = MultiOutputClassifier(SGDClassifier(learning_rate='invscaling', eta0=0.01))
elif (ml_algorithm == "Gaussian_N_Bayes"):
  algorithm = MultiOutputClassifier(GaussianNB())
elif (ml_algorithm == "Multinomial_N_Bayes"):
  algorithm = MultiOutputClassifier(MultinomialNB())
elif (ml_algorithm == "Bernoulli_N_Bayes"):
  algorithm = MultiOutputClassifier(BernoulliNB())
elif (ml_algorithm == "Categorical_N_Bayes"):
  algorithm = MultiOutputClassifier(CategoricalNB())
elif (ml_algorithm == "GradBoost"):
  algorithm = MultiOutputClassifier(GradientBoostingClassifier())
elif (ml_algorithm == "DeciTree"):
  algorithm = MultiOutputClassifier(DecisionTreeClassifier())
elif (ml_algorithm == "RandFrst"):
  algorithm = MultiOutputClassifier(RandomForestClassifier(n_estimators=100))
elif (ml_algorithm == "ExtraTree"):
  algorithm = MultiOutputClassifier(ExtraTreesClassifier(n_estimators=100))
elif (ml_algorithm == "KNN"):
  algorithm = MultiOutputClassifier(KNeighborsClassifier(n_neighbors=6, weights='distance'))
elif (ml_algorithm == "DL_MLP"): # NOT WORKING
  algorithm = MLPClassifier(hidden_layer_sizes=(standized_X_train.shape[1], 30, 50, 10, standized_y_train.shape[1]), activation='relu', solver='lbfgs', learning_rate='constant', learning_rate_init=0.001)


# TRAINING: K-Fold Cross-Validation. Fit algorithm(ML) to data(Training).
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score, matthews_corrcoef

cv_preds = cross_val_predict(algorithm, standized_X_train, standized_y_train, cv=3, method='predict')
print("Shape of Output/Predictions: ", cv_preds.shape, "\n")
reversed_y_train = pd.DataFrame(cv_preds)
reversed_y_train = np.rint(reversed_y_train).astype(np.int32)

# Evaluate model's performance. Overfitting(Train ERR << Test ERR); Underfitting(Train ERR >> Test ERR).
raw_y_train = y_train.values[:,:]
acc = accuracy_score(raw_y_train, reversed_y_train, normalize=True)  # normalize=True(fraction of correctly classified samples); normalize=False(no. of correctly classified samples)
pr_rc_fs_sp = precision_recall_fscore_support(raw_y_train, reversed_y_train, average='weighted')  # average='weighted'(compute metrics per label, and find their avg. weighted by support (no. of true instances per label))
mcc = matthews_corrcoef(raw_y_train, reversed_y_train)
algorithm.fit(standized_X_train, standized_y_train)
pred_scr = algorithm.predict_proba(standized_X_train)[0]
roc = roc_auc_score(raw_y_train, pred_scr[:,1], average='weighted', multi_class='ovo')  # multi_class='ovo'(meaning One-vs-one. Computes avg. AUC of all possible pairwise combinations of classes)

# Training Metrics
print("Training Metrics: ", "\n----------------")
print("ACCURACY: ", acc)
print("PRECISION: ", pr_rc_fs_sp[0])
print("RECALL: ", pr_rc_fs_sp[1])
print("F1-SCORE: ", pr_rc_fs_sp[2])
print("AREA under ROC: ", roc)
print("MCC: ", mcc)
print()

# TESTING/GENERALIZATION: Make Predictions for 'y-component' wrt. data(Test)
model = algorithm
model.fit(standized_X_train, standized_y_train)
pred_y_test = model.predict(standized_X_test)
reversed_y_test = pd.DataFrame(pred_y_test)
reversed_y_test = np.rint(reversed_y_test).astype(np.int32)

# Evaluate model's performance. Overfitting(Train ERR << Test ERR); Underfitting(Train ERR >> Test ERR).
raw_y_test = y_test.values[:,:]
acc = accuracy_score(raw_y_test, reversed_y_test, normalize=True)  # normalize=True(fraction of correctly classified samples); normalize=False(no. of correctly classified samples)
pr_rc_fs_sp = precision_recall_fscore_support(raw_y_test, reversed_y_test, average='weighted')  # average='weighted'(compute metrics per label, and find their avg. weighted by support (no. of true instances per label))
mcc = matthews_corrcoef(raw_y_test, reversed_y_test)
pred_scr = model.predict_proba(standized_X_test)[0]
roc = roc_auc_score(raw_y_test, pred_scr[:,1], average='weighted', multi_class='ovo')  # multi_class='ovo'(meaning One-vs-one. Computes avg. AUC of all possible pairwise combinations of classes)

# Testing Metrics
print("Testing Metrics: ", "\n----------------")
print("ACCURACY: ", acc)
print("PRECISION: ", pr_rc_fs_sp[0])
print("RECALL: ", pr_rc_fs_sp[1])
print("F1-SCORE: ", pr_rc_fs_sp[2])
print("AREA under ROC: ", roc)
print("MCC: ", mcc)

# Confusion Matrix
cnf_matrix = metrics.confusion_matrix(y_test, pred_y_test)
p = sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.show()